site_name: Subsquid
docs_dir: ./src
nav:
  - Home: index.md
  - Quick start: quickstart.md
  - Key-Concepts: 
    - Architecture: key-concepts/architecture.md
    - Processor: key-concepts/processor.md
    - Substrate: key-concepts/substrate.md
    - Typegen: key-concepts/typegen.md
  - Guides:
    - Migrate to V5: guides/migrate-to-v5.yml
    - How to Launch a Squid Archive: guides/how-to-launch-a-squid-archive.md
theme:
  name: material
